### ISSUE TITLE
Minor grammar change

### ISSUE THREAD

**Issue by enotsluap** [unfolddata/ogdd#18]
Focus Area text for when mouse is on "Licensing" (on the right-hand side):
Remove comma and 's' on the end of contracts
so that it reads "... publication and contract renewals."

**Comment by tmfrnz** [comment]
@enotsluap the focus area descriptions come out of the indicators.csv file that will be hosted with data.govt. Just make sure to update the csv file accordingly before publishing it.

**Comment by tmfrnz** [comment]
@enotsluap have updated the csv file in this repository and will have @camfindlay update the data.govt test data accordingly
