### ISSUE TITLE
Harmonise styles with data.govt header template

### ISSUE THREAD

**Issue by tmfrnz** [unfolddata/ogdd#23]
New data.govt header content (logo and back-link) are within content container, limited to a width of 940px. Ideally dashboard app content should also be limited to same width. 

### Header

- [x] consider limiting content width to 940px 
- [x] consider removing logo graphic (will still need application name)

### General

- [x] consider using data.govt font "fira sans"

**Comment by tmfrnz** [comment]
@camfindlay we have adjusted some design and styles to better match the data.govt template - you can re-deploy a WIP version from https://github.com/unfolddata/ogdd/tree/master/dist but please note that the application now requires the more specific root tag `<div id="ogdd-root"></div>` (#27)

With regards to the design and styles we suggest the following:

- limit content width to 940px but allow dashboard to occupy full width to allow for header bar optic (shadow must run all the way through to not appear broken)
- also align header content with content width, but split logo graphic in 2 parts: 
  - application title aligned with content (this is important and should not be removed)
  - logo graphic aligned left with viewport (will float behind title in small screens)
- we find the 'Fira Sans' font not very suitable for use in dashboards and data visualisations as its overall appearance is very vivid, bouncy and active and thus competes for attention (@dmprk can provide more details if needed). If possible we would prefer to have Google's 'Barlow' whitelisted.
- SVG graphics are now being inlined and should no longer be flagged by CSP (#26)

**Comment by tmfrnz** [comment]
You can also see the latest version on GitHub Pages: https://unfolddata.github.io/ogdd/

**Comment by camfindlay** [comment]
I see the dash specific logo has been retained -is this still to be removed?

**Comment by camfindlay** [comment]
Can confirm the svg graphics are working as expected.

**Comment by camfindlay** [comment]
I need to make some adjustments to styles on the minimal data.govt.nz header but overall fits much better.

**Comment by tmfrnz** [comment]
yes @camfindlay, if you do not mind we would like to retain the dash specific logo, but align the all the header wording

**Comment by camfindlay** [comment]
no worries, we'll retain the logo. tested on CWP, I think we can just about run with this release.

**Comment by tmfrnz** [comment]
@camfindlay did you by the way also white-list the 'Barlow' font? (see above for details)

**Comment by camfindlay** [comment]
font is fine. Let me know when you've fix minors at your end and I'll pick up here.

**Comment by tmfrnz** [comment]
@camfindlay just to let you know that we are pretty much final and addressed everything we planned to / we were aware of, so you can go ahead and grab the index.js and update your test page once more if you like. If you are happy and don't experience any further issues, the only changes should concern the data or the content (latter would require a re-build).

**Comment by camfindlay** [comment]
Other than updating the insights dataset, was there any thing else on your side that will require a rebuild of the index.js?

Otheriwse I'm going to roll a new install and we can deal with the repo handover at a later point (we'll deploy from our fork).

**Comment by tmfrnz** [comment]
There is nothing on our side that would require a rebuild but I am not sure if @enotsluap and his team have any other change requests (or have considered #30).

Of course the dashboard should not be made public until final go ahead from @enotsluap.

**Comment by camfindlay** [comment]
updates in draft - this issue can be closed.
