### ISSUE TITLE
Make root tag more specific

### ISSUE THREAD

**Issue by tmfrnz** [unfolddata/ogdd#27]
Change `#root` entry tag to something more specific, eg `#ogdd-root`

- [x] src/index.js
- [x] src/global-styles.js
- [x] src/index.html (during development)
- [x] .ss template

**Comment by camfindlay** [comment]
updated in ss

**Comment by camfindlay** [comment]
Can close this issue.

**Comment by tmfrnz** [comment]
Thanks Cam
