### ISSUE TITLE
Typo in 2017 key insight

### ISSUE THREAD

**Issue by tmfrnz** [unfolddata/ogdd#28]
> 72%
work with **orther** organisations in their sector to promote the value of specific datasets or open data in general

**Comment by tmfrnz** [comment]
Have fixed typo in repository data (https://github.com/unfolddata/ogdd/commit/6b4fd57830041983317d7e01fa54d81b68ec2e91)

@camfindlay could you update the insights table on data.govt?

**Comment by camfindlay** [comment]
This will correct itself once we put the data up on data.govt.nz proper.
