### ISSUE TITLE
Typo in key insights table

### ISSUE THREAD

**Issue by tmfrnz** [unfolddata/ogdd#29]
`ki2017-03,2017,q28,62,do not or are note ...`

should be 

`ki2017-03,2017,q28,62,do not or are not ...`

**Comment by tmfrnz** [comment]
Hi @camfindlay, when you get the chance could you once more update the insights table?

**Comment by tmfrnz** [comment]
Hi @camfindlay, when you get the chance could you once more update the insights table?

From: https://github.com/unfolddata/ogdd/blob/master/data/insights.csv

**Comment by camfindlay** [comment]
I'll do a final data refresh once you're happy everything else is ready to go.

**Comment by camfindlay** [comment]
Dataset has been updated. you can close this.
