### ISSUE TITLE
Small suggestion for 'indicators' table: consistent use of '&' for focus area names

### ISSUE THREAD

**Issue by tmfrnz** [unfolddata/ogdd#30]
@enotsluap there is one more minor suggestion I would have regarding the focus area names:

Where some feature the '&', namely

- Knowledge **&** skills
- Stakeholder engagement **&** support

there is one that uses "and"

- Investment **and** financial performance

Let me know if you would like me to update this here in the repo and then have @camfindlay update the data on data.govt?

**Comment by camfindlay** [comment]
just use "&" and more along ;)

**Comment by tmfrnz** [comment]
updated in CSV file as discussed via email. 

@camfindlay when you have the chance, can you update the resource "indicators" on data.govt from https://github.com/unfolddata/ogdd/blob/master/data/indicators.csv? THANKS

**Comment by camfindlay** [comment]
Hi @tmfrnz just to check you need 1) update on the indicators data and 2) for me to grab the latest js distro?

**Comment by tmfrnz** [comment]
Hi @camfindlay, 

If you haven't done so in the past 3 days then YES to both. Thanks!

**Comment by camfindlay** [comment]
data updated about to grab the new bundle. I think these can be closed.
