### ISSUE TITLE
Data.govt API server error: BAD GATEWAY

### ISSUE THREAD

**Issue by tmfrnz** [unfolddata/ogdd#31]
@camfindlay not sure what exactly may have caused this but I received this BAD GATEWAY error when accessing the surveys.csv resource:

> `HTTP502: BAD GATEWAY - The server, while acting as a gateway or proxy, received an invalid response from the upstream server it accessed in attempting to fulfil the request.
GET - https://catalogue.data.govt.nz/api/3/action/datastore_search?resource_id=1578c5cc-fcfc-41ae-a61b-5f8f3467d437&limit=999999&callback=jsonp_1535004334745_80088`

The second load attempt was successful (as of today the application will try loading 5 times before giving up) so this is not so much an issue for the dashboard

**Comment by camfindlay** [comment]
Thanks, we will have captured this in our monitoring. Let me know if it was a once off or is happening regularly.

**Comment by tmfrnz** [comment]
I have only noticed this a couple of times so far but will let you know if I see it more regularly. Closing this for now...
